{% set version = "0.4.0" %}
{% set python_min = "3.11" %}

package:
  name: beam-corset
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/b/beam-corset/beam_corset-{{ version }}.tar.gz
  sha256: 3004bccddb4521bc9d5e33030e21d09cc3c85b41c1eb1d10cb226904be105429

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - ipywidgets >=8.1.8,<9
    - matplotlib-base >=3.10.7,<4
    - numpy >=2.3.4,<3
    - pandas >=2.3.3,<3
    - pyyaml >=6.0.3,<7
    - scipy >=1.16.3,<2
    - tqdm >=4.67.3,<5

test:
  imports:
    - corset
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://lkies.github.io/corset/
  summary: Beam Corset is a Gaussian optics mode matching tool made for use in Jupyter notebooks.
  dev_url: https://github.com/lkies/corset
  doc_url: https://lkies.github.io/corset/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - lkies
